### ISSUE TITLE
Superset asset translations has element not translated

### ISSUE THREAD

**Issue by Ian2012** [openedx/tutor-contrib-aspects#252]
This issue recovers most of the elements that still needs translations:

- Header
```
    HEADER--KqHmCf5Bg:
      children: []
      id: HEADER--KqHmCf5Bg
      meta:
        background: BACKGROUND_TRANSPARENT
        headerSize: MEDIUM_HEADER
        text: Some text
      parents:
      - ROOT_ID
      - GRID_ID
      type: HEADER
```
- Markdown: ??
- Chart description
